--------------------------------------------------------
--  File created - Tuesday-June-03-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACC_ALLOCATIONS_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_ALLOCATIONS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_ALLOCATION_ARTICLES_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_ALLOCATION_ARTICLES_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_ALLOCATION_PAYS_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_ALLOCATION_PAYS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_CREDITS_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_CREDITS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_CURRENCY_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_CURRENCY_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_KINDS_STORE_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_KINDS_STORE_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 91 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_LOOKUP_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_LOOKUP_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_MINUS_HEADERS_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_MINUS_HEADERS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_MINUS_SITES_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_MINUS_SITES_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 301 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_OPPORTUNITY_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_OPPORTUNITY_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACC_POCKETS_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."ACC_POCKETS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 111 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence PPL_PEOPLES_S
--------------------------------------------------------

   CREATE SEQUENCE  "ASSISTANT"."PPL_PEOPLES_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table ACC_ALLOCATIONS_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" 
   (	"ID_" NUMBER, 
	"NAME_" VARCHAR2(500 CHAR), 
	"ARTICLE_ID_" NUMBER, 
	"DATE_" DATE, 
	"SUMM_" NUMBER, 
	"CURREN_" VARCHAR2(3 CHAR), 
	"MANDATORY_" VARCHAR2(1 CHAR), 
	"ACTIVE_" VARCHAR2(1 CHAR), 
	"MANUAL_" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_ALLOCATION_ARTICLES_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" 
   (	"ID_" NUMBER, 
	"NAME_" VARCHAR2(500 CHAR), 
	"PERIODICAL_" VARCHAR2(500 CHAR), 
	"START_DATE_" DATE, 
	"ACTIVE_" VARCHAR2(1 CHAR), 
	"PARENT_ARTICLE_ID_" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_ALLOCATION_PAYS_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" 
   (	"ID_" NUMBER, 
	"ALLOC_ID_" NUMBER, 
	"SUMM_" NUMBER, 
	"CURREN_" VARCHAR2(3 CHAR), 
	"POCKET_ID_" NUMBER, 
	"ACTIVE_" VARCHAR2(1 CHAR), 
	"SUMM_MINUS_" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_CREDITS_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_CREDITS_T" 
   (	"ID_" NUMBER, 
	"WHO_ID_" NUMBER, 
	"SUMM_" NUMBER, 
	"CURREN_" VARCHAR2(3 CHAR), 
	"DEAD_LINE_" DATE, 
	"POCKET_ID_" NUMBER, 
	"PROFIT_TYPE_" VARCHAR2(10 CHAR), 
	"PROFIT_VALUE_" NUMBER, 
	"WHEN_" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_CURRENCY_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_CURRENCY_T" 
   (	"NAME_" VARCHAR2(10 CHAR), 
	"ABRIVEATURE_" VARCHAR2(3 CHAR), 
	"QOUTE_" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_KINDS_STORE_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_KINDS_STORE_T" 
   (	"ID_" NUMBER, 
	"NAME_" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_LOOKUP_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_LOOKUP_T" 
   (	"ID_" NUMBER, 
	"NAME_" VARCHAR2(50 CHAR), 
	"VALUE_DISPLAY_" VARCHAR2(100 CHAR), 
	"VALUE_RETURN_" VARCHAR2(100 CHAR), 
	"OUTPUT_PRIORITET_" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_MINUS_HEADERS_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_MINUS_HEADERS_T" 
   (	"ID_" NUMBER, 
	"ALLOC_ID_" NUMBER, 
	"DATE_" DATE, 
	"SUMM_" NUMBER, 
	"COMMENT_" VARCHAR2(200 CHAR), 
	"CURR_QUOTE_" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_MINUS_SITES_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_MINUS_SITES_T" 
   (	"ID_" NUMBER, 
	"ALLOC_PAY_ID_" NUMBER, 
	"SUMM_" NUMBER, 
	"COMMENT_" VARCHAR2(200 CHAR), 
	"MINUS_ID_" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_OPPORTUNITY_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" 
   (	"ID_" NUMBER, 
	"NAME_" VARCHAR2(1000 CHAR), 
	"DATE_" DATE, 
	"VARIATY_" NUMBER, 
	"SUMM_" NUMBER, 
	"CURREN_" VARCHAR2(3 CHAR), 
	"COMMENTS_" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table ACC_POCKETS_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."ACC_POCKETS_T" 
   (	"ID_" NUMBER, 
	"NAME_" VARCHAR2(200 CHAR), 
	"KIND_STORE_ID_" NUMBER, 
	"SUMM_" NUMBER, 
	"CURREN_" VARCHAR2(3 CHAR), 
	"ACTIVE_" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for Table PPL_PEOPLES_T
--------------------------------------------------------

  CREATE TABLE "ASSISTANT"."PPL_PEOPLES_T" 
   (	"ID_" NUMBER, 
	"FAMILY_" VARCHAR2(20 CHAR), 
	"NAME_" VARCHAR2(20 CHAR), 
	"FATHER_NAME_" VARCHAR2(20 CHAR), 
	"BIRTHDAY_" DATE, 
	"COMMENTS_" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_2398132084544616" ;
--------------------------------------------------------
--  DDL for View ACC_ALLOCATIONS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ASSISTANT"."ACC_ALLOCATIONS_V" ("ID_", "NAME_", "ARTICLE_ID_", "ARTICLE_NAME_", "DATE_", "SUMM_", "SUMM_HAVE_", "SUMM_HAVE_PROCENT_", "SUMM_MIN_", "CURREN_", "MANDATORY_", "ACTIVE_") AS 
  select a.id_,
       a.name_,
       a.article_id_ article_id_,
       aa.name_ article_name_,
       a.date_,
       a.summ_,
       nvl((select sum(ap.summ_) - sum(summ_minus_)
             from acc_allocation_pays_t ap
            where ap.alloc_id_ = a.id_
              and ap.active_ = 'Y'),
           0) summ_have_,
       nvl(round((select sum(ap.summ_) - sum(summ_minus_)
                    from acc_allocation_pays_t ap
                   where ap.alloc_id_ = a.id_
                     and ap.active_ = 'Y') * 100 / a.summ_,
                 2),
           0) || '%' summ_have_procent_,
       nvl((select sum(m.summ_)
             from acc_minus_headers_t m
            where m.alloc_id_ = a.id_),
           0) summ_min_,
       a.curren_,
       a.mandatory_,
       a.active_ active_
  from acc_allocations_t a, acc_allocation_articles_t aa
 where a.article_id_ = aa.id_;
--------------------------------------------------------
--  DDL for View ACC_ALLOCATION_ARTICLS_HRCHY_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ASSISTANT"."ACC_ALLOCATION_ARTICLS_HRCHY_V" ("NAME_HIERARCHY", "ID_", "PARENT_ARTICLE_ID_", "LVL", "NAME_", "PERIODICAL_", "START_DATE_", "ACTIVE_") AS 
  SELECT LPAD(' ', 2*(level-1),'- ')
  ||aa.name_ name_hierarchy,
  aa.id_ id_,
  aa.PARENT_ARTICLE_ID_ PARENT_ARTICLE_ID_,
  LEVEL lvl,
  aa.name_ name_ ,
  aa.PERIODICAL_ PERIODICAL_,
  aa.start_date_ start_date_,
  aa.Active_ Active_
FROM ACC_ALLOCATION_ARTICLES_T aa
  CONNECT BY PRIOR aa.ID_ = aa.PARENT_ARTICLE_ID_
  START WITH aa.ID_       = 0;
--------------------------------------------------------
--  DDL for View ACC_ALLOCATION_PAYS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ASSISTANT"."ACC_ALLOCATION_PAYS_V" ("ID_", "ALLOC_ID_", "SUMM_PAY_", "CURREN_", "POCKET_ID_", "ALLOC_NAME_", "ALLOC_ARTICLE_NAME_", "ALLOC_DATE_", "SUMM_ALLOC_", "ALLOC_SUMM_HAVE_", "ALLOC_SUMM_HAVE_PROCENT_", "ALLOC_CUREN_", "ALLOC_MANDATORY_", "ALLOC_ACTIVE_", "PCK_SUMM_BUSY_", "PCK_SUMM_AVLB_", "SUMM_MINUS_", "ACTIVE_", "PCK_NAME_", "PCK_KIND_STORE_ID_", "PCK_SUMM_", "PCK_ACTIVE_") AS 
  select ap.id_,
       ap.alloc_id_,
       ap.summ_             summ_pay_,
       ap.curren_,
       ap.pocket_id_,
       a.name_              alloc_name_,
       a.article_name_      alloc_article_name_,
       a.date_              alloc_date_,
       a.summ_              summ_alloc_,
       a.summ_have_         alloc_summ_have_,
       a.summ_have_procent_ alloc_summ_have_procent_,
       a.curren_            alloc_curen_,
       a.mandatory_         alloc_mandatory_,
       a.active_            alloc_active_,
       p.summ_busy_         pck_summ_busy_,
       p.summ_avlb_         pck_summ_avlb_,
       ap.summ_minus_,
       ap.active_,
       p.name_              pck_name_,
       p.kind_store_id_     pck_kind_store_id_,
       p.summ_              pck_summ_,
       p.active_            pck_active_
  from acc_allocation_pays_t ap, acc_allocations_v a, acc_pockets_v p
 where a.id_ = ap.alloc_id_
   and p.id_ = ap.pocket_id_;
--------------------------------------------------------
--  DDL for View ACC_POCKETS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ASSISTANT"."ACC_POCKETS_V" ("ID_", "NAME_", "KIND_STORE_ID_", "KIND_STORE_NAME_", "SUMM_", "SUMM_BUSY_", "SUMM_AVLB_", "CURREN_", "ACTIVE_") AS 
  select p.id_ id_,
       p.name_ name_,
       p.kind_store_id_ kind_store_id_,
       ks.name_ kind_store_name_,
       p.summ_ summ_,
       (select nvl(sum(ap.summ_),0)
          from assistant.acc_allocation_pays_t ap
         where p.id_ = ap.pocket_id_) summ_busy_,
       (p.summ_ - (select nvl(sum(ap.summ_),0)
                     from assistant.acc_allocation_pays_t ap
                    where p.id_ = ap.pocket_id_)) summ_avlb_,
       p.curren_ curren_,
       p.active_
  from assistant.acc_pockets_t p, assistant.acc_kinds_store_t ks
  where p.kind_store_id_ = ks.id_;
REM INSERTING into ASSISTANT.ACC_LOOKUP_T
SET DEFINE OFF;
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (31,'ACC_OBJECTS_PARENT_COLUMNS','ALLOCATION_PAY','ALLOC_PAY_ID_',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (21,'ACC_OBJECTS_PARENT_COLUMNS','KIND_STORE','KIND_STORE_ID_',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (22,'ACC_OBJECTS_PARENT_COLUMNS','ALLOCATION','ALLOC_ID_',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (23,'ACC_OBJECTS_PARENT_COLUMNS','POCKET','POCKET_ID_',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (24,'ACC_OBJECTS_PARENT_COLUMNS','ALLOCATION_ARTICLE','ARTICLE_ID_',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (1,'Y|N','Да','Y',1);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (2,'Y|N','Нет','N',2);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (11,'ACC_OBJECTS','POCKET','ACC_POCKETS_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (12,'ACC_OBJECTS','MINUS_HEADERS','ACC_MINUS_HEADERS_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (13,'ACC_OBJECTS','ALLOCATION_PAY','ACC_ALLOCATION_PAYS_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (14,'ACC_OBJECTS','ALLOCATION_ARTICLE','ACC_ALLOCATION_ARTICLES_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (15,'ACC_OBJECTS','ALLOCATION','ACC_ALLOCATIONS_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (16,'ACC_OBJECTS','CREDIT','ACC_CREDITS_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (17,'ACC_OBJECTS','KIND_STORE','ACC_KINDS_STORE_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (18,'ACC_OBJECTS','OPPORTUNITY','ACC_OPPORTUNITY_T',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (41,'ACC_OBJECTS_PARENT_COLUMNS','MINUS_HEADERS','MINUS_ID_',null);
Insert into ASSISTANT.ACC_LOOKUP_T (ID_,NAME_,VALUE_DISPLAY_,VALUE_RETURN_,OUTPUT_PRIORITET_) values (25,'ACC_OBJECTS_PARENT_COLUMNS','NONE','ID_',null);
--------------------------------------------------------
--  DDL for Index ACC_LOOKUP_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."ACC_LOOKUP_PK1" ON "ASSISTANT"."ACC_LOOKUP_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACC_LOOKUP_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."ACC_LOOKUP_UK1" ON "ASSISTANT"."ACC_LOOKUP_T" ("NAME_", "VALUE_DISPLAY_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOCATION_PAYS__PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."ALLOCATION_PAYS__PK" ON "ASSISTANT"."ACC_ALLOCATION_PAYS_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."ALLOCATION_PK" ON "ASSISTANT"."ACC_ALLOCATIONS_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOCATION_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."ALLOCATION_UN" ON "ASSISTANT"."ACC_ALLOCATIONS_T" ("NAME_", "ARTICLE_ID_", "DATE_", "SUMM_", "CURREN_", "MANDATORY_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARTICLES_ALLOC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."ARTICLES_ALLOC_PK" ON "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARTICLES_ALLOC__UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."ARTICLES_ALLOC__UN" ON "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" ("NAME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CREDITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."CREDITS_PK" ON "ASSISTANT"."ACC_CREDITS_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURRENCY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."CURRENCY_PK" ON "ASSISTANT"."ACC_CURRENCY_T" ("NAME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURRENCY_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."CURRENCY_UN" ON "ASSISTANT"."ACC_CURRENCY_T" ("ABRIVEATURE_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KINDS_STORE__PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."KINDS_STORE__PK" ON "ASSISTANT"."ACC_KINDS_STORE_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KINDS_STORE___UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."KINDS_STORE___UN" ON "ASSISTANT"."ACC_KINDS_STORE_T" ("NAME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MINUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."MINUS_PK" ON "ASSISTANT"."ACC_MINUS_HEADERS_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MINUS_SITES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."MINUS_SITES_PK" ON "ASSISTANT"."ACC_MINUS_SITES_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MINUS_SITES_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."MINUS_SITES_UK" ON "ASSISTANT"."ACC_MINUS_SITES_T" ("MINUS_ID_", "ALLOC_PAY_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OPPORTUNITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."OPPORTUNITY_PK" ON "ASSISTANT"."ACC_OPPORTUNITY_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OPPORTUNITY_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."OPPORTUNITY_UN" ON "ASSISTANT"."ACC_OPPORTUNITY_T" ("NAME_", "DATE_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEOPLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."PEOPLES_PK" ON "ASSISTANT"."PPL_PEOPLES_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POCKETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."POCKETS_PK" ON "ASSISTANT"."ACC_POCKETS_T" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POCKETS__UNV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASSISTANT"."POCKETS__UNV1" ON "ASSISTANT"."ACC_POCKETS_T" ("NAME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACC_ALLOCATIONS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("ARTICLE_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("DATE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("SUMM_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("CURREN_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("MANDATORY_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("ACTIVE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" MODIFY ("MANUAL_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" ADD CONSTRAINT "ALLOCATION_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" ADD CONSTRAINT "ALLOCATION_UN" UNIQUE ("NAME_", "ARTICLE_ID_", "DATE_", "SUMM_", "CURREN_", "MANDATORY_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_ALLOCATION_ARTICLES_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" MODIFY ("NAME_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" MODIFY ("START_DATE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" MODIFY ("ACTIVE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" ADD CONSTRAINT "ARTICLES_ALLOC_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" ADD CONSTRAINT "ARTICLES_ALLOC__UN" UNIQUE ("NAME_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_ALLOCATION_PAYS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" MODIFY ("ALLOC_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" MODIFY ("CURREN_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" MODIFY ("POCKET_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" MODIFY ("ACTIVE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" MODIFY ("SUMM_MINUS_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" ADD CONSTRAINT "ALLOCATION_PAYS__PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_CREDITS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" MODIFY ("WHO_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" MODIFY ("SUMM_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" MODIFY ("CURREN_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" MODIFY ("POCKET_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" ADD CONSTRAINT "CREDITS_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_CURRENCY_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_CURRENCY_T" MODIFY ("NAME_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CURRENCY_T" MODIFY ("ABRIVEATURE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CURRENCY_T" MODIFY ("QOUTE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_CURRENCY_T" ADD CONSTRAINT "CURRENCY_PK" PRIMARY KEY ("NAME_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_CURRENCY_T" ADD CONSTRAINT "CURRENCY_UN" UNIQUE ("ABRIVEATURE_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_KINDS_STORE_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_KINDS_STORE_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_KINDS_STORE_T" MODIFY ("NAME_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_KINDS_STORE_T" ADD CONSTRAINT "KINDS_STORE__PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_KINDS_STORE_T" ADD CONSTRAINT "KINDS_STORE___UN" UNIQUE ("NAME_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_LOOKUP_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_LOOKUP_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_LOOKUP_T" MODIFY ("NAME_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_LOOKUP_T" MODIFY ("VALUE_DISPLAY_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_LOOKUP_T" MODIFY ("VALUE_RETURN_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_LOOKUP_T" ADD CONSTRAINT "ACC_LOOKUP_PK1" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_LOOKUP_T" ADD CONSTRAINT "ACC_LOOKUP_UK1" UNIQUE ("NAME_", "VALUE_DISPLAY_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_MINUS_HEADERS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_MINUS_HEADERS_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_HEADERS_T" MODIFY ("ALLOC_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_HEADERS_T" MODIFY ("DATE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_HEADERS_T" MODIFY ("SUMM_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_HEADERS_T" ADD CONSTRAINT "MINUS_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_MINUS_SITES_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" MODIFY ("ALLOC_PAY_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" MODIFY ("SUMM_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" MODIFY ("MINUS_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" ADD CONSTRAINT "MINUS_SITES_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" ADD CONSTRAINT "MINUS_SITES_UK" UNIQUE ("MINUS_ID_", "ALLOC_PAY_ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_OPPORTUNITY_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" MODIFY ("NAME_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" MODIFY ("DATE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" MODIFY ("VARIATY_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" MODIFY ("SUMM_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" MODIFY ("CURREN_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" ADD CONSTRAINT "OPPORTUNITY_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" ADD CONSTRAINT "OPPORTUNITY_UN" UNIQUE ("NAME_", "DATE_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACC_POCKETS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" MODIFY ("KIND_STORE_ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" MODIFY ("SUMM_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" MODIFY ("CURREN_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" MODIFY ("ACTIVE_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" ADD CONSTRAINT "POCKETS_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" ADD CONSTRAINT "POCKETS__UNV1" UNIQUE ("NAME_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPL_PEOPLES_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."PPL_PEOPLES_T" MODIFY ("ID_" NOT NULL ENABLE);
  ALTER TABLE "ASSISTANT"."PPL_PEOPLES_T" ADD CONSTRAINT "PEOPLES_PK" PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACC_ALLOCATIONS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" ADD CONSTRAINT "ALLOC_ARTICLES_ALLOC_FK" FOREIGN KEY ("ARTICLE_ID_")
	  REFERENCES "ASSISTANT"."ACC_ALLOCATION_ARTICLES_T" ("ID_") ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATIONS_T" ADD CONSTRAINT "ALLOC_CURRENCY_FK" FOREIGN KEY ("CURREN_")
	  REFERENCES "ASSISTANT"."ACC_CURRENCY_T" ("ABRIVEATURE_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACC_ALLOCATION_PAYS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" ADD CONSTRAINT "ALLOC_PAYS_ALLOCATIONS_FK" FOREIGN KEY ("ALLOC_ID_")
	  REFERENCES "ASSISTANT"."ACC_ALLOCATIONS_T" ("ID_") ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_ALLOCATION_PAYS_T" ADD CONSTRAINT "ALLOC_PAYS_POCKETS_FK" FOREIGN KEY ("POCKET_ID_")
	  REFERENCES "ASSISTANT"."ACC_POCKETS_T" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACC_CREDITS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" ADD CONSTRAINT "CREDITS__PEOPLES__FK" FOREIGN KEY ("WHO_ID_")
	  REFERENCES "ASSISTANT"."PPL_PEOPLES_T" ("ID_") ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_CREDITS_T" ADD CONSTRAINT "CREDITS__POCKETS__FK" FOREIGN KEY ("POCKET_ID_")
	  REFERENCES "ASSISTANT"."ACC_POCKETS_T" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACC_MINUS_HEADERS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_MINUS_HEADERS_T" ADD CONSTRAINT "MINUS_ALLOCATION_FK" FOREIGN KEY ("ALLOC_ID_")
	  REFERENCES "ASSISTANT"."ACC_ALLOCATIONS_T" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACC_MINUS_SITES_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" ADD CONSTRAINT "MINUS_SITES_ALLOCATIONS_FK" FOREIGN KEY ("ALLOC_PAY_ID_")
	  REFERENCES "ASSISTANT"."ACC_ALLOCATION_PAYS_T" ("ID_") ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_MINUS_SITES_T" ADD CONSTRAINT "MINUS_SITES_MINUS_FK" FOREIGN KEY ("MINUS_ID_")
	  REFERENCES "ASSISTANT"."ACC_MINUS_HEADERS_T" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACC_OPPORTUNITY_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_OPPORTUNITY_T" ADD CONSTRAINT "OPPORTUNITY_CURRENCY_FK" FOREIGN KEY ("CURREN_")
	  REFERENCES "ASSISTANT"."ACC_CURRENCY_T" ("ABRIVEATURE_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACC_POCKETS_T
--------------------------------------------------------

  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" ADD CONSTRAINT "POCKETS_CURRENCY__FK" FOREIGN KEY ("CURREN_")
	  REFERENCES "ASSISTANT"."ACC_CURRENCY_T" ("ABRIVEATURE_") ENABLE;
  ALTER TABLE "ASSISTANT"."ACC_POCKETS_T" ADD CONSTRAINT "POCKETS_KINDS_STORE__FK" FOREIGN KEY ("KIND_STORE_ID_")
	  REFERENCES "ASSISTANT"."ACC_KINDS_STORE_T" ("ID_") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_ALLOCATIONS_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_ALLOCATIONS_ADD" 
before insert on assistant.acc_allocations_t
for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_allocations_s.nextval
      into :new.id_
      from dual;
  end if;  
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_ALLOCATIONS_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_ALLOCATION_ARTICLES_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_ALLOCATION_ARTICLES_ADD" 
before insert on assistant.acc_allocation_articles_t
for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_allocation_articles_s.nextval
      into :new.id_
      from dual;
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_ALLOCATION_ARTICLES_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_ALLOCATION_PAYS_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_ALLOCATION_PAYS_ADD" 
  before insert on assistant.acc_allocation_pays_t
  for each row
declare
begin

  if :new.id_ is null then
    select assistant.acc_allocation_pays_s.nextval into :new.id_ from dual;
  end if;

  if :new.active_ is null then
    :new.active_ := 'Y';
  end if;

end;
/
ALTER TRIGGER "ASSISTANT"."ACC_ALLOCATION_PAYS_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_CREDITS_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_CREDITS_ADD" 
  before insert or update on assistant.acc_credits_t
  for each row
declare
  v_pck assistant.acc_pockets_v%rowtype;
begin
  if :new.id_ is null then
      select assistant.acc_credits_s.nextval into :new.id_ from dual;
    end if;
  select *
    into v_pck
    from assistant.acc_pockets_v p
   where :new.pocket_id_ = p.id_;
   
  :new.curren_ := v_pck.curren_;
  
  if :new.summ_ <= v_pck.summ_avlb_ then
    :new.curren_ := v_pck.curren_;
  else
  null;
  end if;
  
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_CREDITS_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_KINDS_STORE_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_KINDS_STORE_ADD" 
before insert on assistant.acc_kinds_store_t
for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_kinds_store_s.nextval
      into :new.id_
      from dual;
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_KINDS_STORE_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_LOOKUP_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_LOOKUP_ADD" 
before insert on assistant.acc_lookup_t
for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_lookup_s.nextval
      into :new.id_
      from dual;
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_LOOKUP_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_MINUS_HEADERS_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_MINUS_HEADERS_ADD" 
before insert on assistant.ACC_MINUS_HEADERS_T
for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_minus_headers_s.nextval
      into :new.id_
      from dual;
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_MINUS_HEADERS_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_MINUS_SITES_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_MINUS_SITES_ADD" 
before insert on assistant.ACC_MINUS_siteS_T
for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_minus_sites_s.nextval
      into :new.id_
      from dual;
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_MINUS_SITES_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_OPPORTUNITY_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_OPPORTUNITY_ADD" 
before insert on assistant.acc_opportunity_t
for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_opportunity_s.nextval
      into :new.id_
      from dual;
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_OPPORTUNITY_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACC_POCKETS_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."ACC_POCKETS_ADD" 
  before insert on assistant.acc_pockets_t
  for each row
declare
begin
  if :new.id_ is null then
    select assistant.acc_pockets_s.nextval into :new.id_ from dual;
  end if;
  if :new.active_ is null then
    :new.active_ := 'Y';
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."ACC_POCKETS_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PPL_PEOPLES_ADD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ASSISTANT"."PPL_PEOPLES_ADD" 
before insert on assistant.PPL_PEOPLES_T
for each row
declare
begin
  if :new.id_ is null then
    select assistant.ppl_peoples_s.nextval
      into :new.id_
      from dual;
  end if;
end;
/
ALTER TRIGGER "ASSISTANT"."PPL_PEOPLES_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Package ACC_CHECKERS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ASSISTANT"."ACC_CHECKERS" is
  -- Author  : DKHARIN
  -- Created : 08.03.2014 21:00:06
  -- Purpose : ACCOUNTENT CHECKERS

  function check_object_exists(p_id                 number,
                               p_object_name        varchar2,
                               p_parent_object_name varchar2) return varchar2;

  function check_object_exists(p_id          number,
                               p_object_name varchar2) return varchar2;

  function check_object_activity(p_id                 number,
                                 p_object_name        varchar2,
                                 p_parent_object_name varchar2)
    return varchar2;

  function check_object_activity(p_id          number,
                                 p_object_name varchar2) return varchar2;

  function check_exsts_act_alloc_by_artcl(p_article_id acc_allocations_t.article_id_%type)
    return varchar2;

end acc_checkers;

/
--------------------------------------------------------
--  DDL for Package ACC_MAIN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ASSISTANT"."ACC_MAIN" is
  -- Author  : DKHARIN
  -- Created : 08.03.2014 18:35:51
  -- Purpose : ACCOUNTENT

  function get_lookup_value(p_lookup_name    varchar2,
                            p_lookup_display varchar2) return varchar2;

  function get_acc_object_currency(p_id number, p_object_name varchar2)
    return varchar2;

  function get_acc_object_summ(p_id number, p_object_name varchar2)
    return varchar2;

  function get_acc_object_table(p_acc_object_name varchar2) return varchar2;

  function get_acc_object_parent_column(p_acc_parent_name varchar2)
    return varchar2;

  function get_currency_qoute(p_abriveature acc_currency_t.abriveature_%type)
    return number;

  procedure allocation_article_add(p_name              acc_allocation_articles_t.name_%type,
                                   p_periodical        acc_allocation_articles_t.periodical_%type,
                                   p_start_date        acc_allocation_articles_t.start_date_%type,
                                   p_parent_article_id acc_allocation_articles_t.parent_article_id_%type);

  procedure allocation_article_upd(p_id                acc_allocation_articles_t.id_%type,
                                   p_name              acc_allocation_articles_t.name_%type,
                                   p_periodical        acc_allocation_articles_t.periodical_%type,
                                   p_start_date        acc_allocation_articles_t.start_date_%type,
                                   p_active            acc_allocation_articles_t.active_%type,
                                   p_parent_article_id acc_allocation_articles_t.parent_article_id_%type);

  procedure allocation_add(p_name       acc_allocations_t.name_%type,
                           p_article_id acc_allocations_t.article_id_%type,
                           p_date       acc_allocations_t.date_%type,
                           p_mandatory  acc_allocations_t.mandatory_%type,
                           p_summ       acc_allocations_t.summ_%type,
                           p_curren     acc_allocations_t.curren_%type);

  procedure allocation_upd(p_id         acc_allocations_t.id_%type,
                           p_name       acc_allocations_t.name_%type,
                           p_article_id acc_allocations_t.article_id_%type,
                           p_date       acc_allocations_t.date_%type,
                           p_mandatory  acc_allocations_t.mandatory_%type,
                           p_summ       acc_allocations_t.summ_%type,
                           p_active     acc_allocations_t.active_%type);

  procedure allocation_pay_add(p_alloc_id  acc_allocation_pays_t.alloc_id_%type,
                               p_summ      acc_allocation_pays_t.summ_%type,
                               p_pocket_id acc_allocation_pays_t.pocket_id_%type);

  procedure allocation_pay_upd(p_id         acc_allocation_pays_t.id_%type,
                               p_summ       acc_allocation_pays_t.summ_%type,
                               p_pocket_id  acc_allocation_pays_t.pocket_id_%type,
                               p_summ_minus acc_allocation_pays_t.summ_minus_%type);

  procedure allocation_pay_deactive(p_id acc_allocation_pays_t.id_%type);

  procedure credit_add(p_who_id       acc_credits_t.who_id_%type,
                       p_summ         acc_credits_t.summ_%type,
                       p_dead_line    acc_credits_t.dead_line_%type,
                       p_pocket_id    acc_credits_t.pocket_id_%type,
                       p_profit_type  acc_credits_t.profit_type_%type,
                       p_profit_value acc_credits_t.profit_value_%type,
                       p_when         acc_credits_t.when_%type);

  procedure kind_store_add(p_name acc_kinds_store_t.name_%type);

  procedure kind_store_upd(p_id   acc_kinds_store_t.id_%type,
                           p_name acc_kinds_store_t.name_%type);

  procedure kind_store_del(p_id acc_kinds_store_t.id_%type);

  procedure pocket_add(p_name          acc_pockets_t.name_%type,
                       p_kind_store_id acc_pockets_t.kind_store_id_%type,
                       p_summ          acc_pockets_t.summ_%type,
                       p_curren        acc_pockets_t.curren_%type);

  procedure pocket_upd(p_id            acc_pockets_t.id_%type,
                       p_name          acc_pockets_t.name_%type,
                       p_kind_store_id acc_pockets_t.kind_store_id_%type,
                       p_summ          acc_pockets_t.summ_%type,
                       p_active        acc_pockets_t.active_%type);

  procedure minus_add(p_alloc_id   acc_minus_headers_t.alloc_id_%type,
                      p_date       acc_minus_headers_t.date_%type,
                      p_summ       acc_minus_headers_t.summ_%type,
                      p_comment    acc_minus_headers_t.comment_%type,
                      p_curr_quote acc_minus_headers_t.curr_quote_%type);

  function minus_header_add(p_alloc_id acc_minus_headers_t.alloc_id_%type,
                            p_date     acc_minus_headers_t.date_%type,
                            p_summ     acc_minus_headers_t.summ_%type,
                            p_comment  acc_minus_headers_t.comment_%type)
    return number;

  procedure minus_sites_add(p_minus_id     acc_minus_sites_t.minus_id_%type,
                            p_alloc_pay_id acc_minus_sites_t.alloc_pay_id_%type,
                            p_summ         acc_minus_sites_t.summ_%type,
                            p_comment      acc_minus_sites_t.comment_%type);
end acc_main;

/
--------------------------------------------------------
--  DDL for Package Body ACC_CHECKERS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ASSISTANT"."ACC_CHECKERS" is
  -- Author  : DKHARIN
  -- Created : 08.03.2014 21:00:06
  -- Purpose : ACCOUNTENT CHECKERS

  function check_object_exists(p_id                 number,
                               p_object_name        varchar2,
                               p_parent_object_name varchar2) return varchar2 as
    v_result number;
    v_sql    varchar2(500char);
    v_id     varchar2(30char);
  begin
    v_id  := acc_main.get_acc_object_parent_column(p_acc_parent_name => p_parent_object_name);
    v_sql := 'select count(1) from dual where exists     
(select p.id_ from ' ||
             acc_main.get_acc_object_table(p_object_name) || ' p where p.' || v_id ||
             ' = ' || p_id || ')';
             
             --------------------------
             DBMS_OUTPUT.PUT_LINE(v_sql);
             --------------------------
             
    execute immediate v_sql
      into v_result;
    if v_result = 1 then
      return 'Y';
    else
      return 'N';
    end if;
  exception
    when others then
      raise_application_error(-20001,'ERROR | CHECK OBJECT EXISTS!!!', true);
  end;

  function check_object_exists(p_id          number,
                               p_object_name varchar2) return varchar2 as
    v_result varchar2(1 char);
  begin
    v_result := check_object_exists(p_id                 => p_id,
                                    p_object_name        => p_object_name,
                                    p_parent_object_name => 'NONE');
    return v_result;
  end;

  function check_object_activity(p_id                 number,
                                 p_object_name        varchar2,
                                 p_parent_object_name varchar2)
    return varchar2 as
    v_result number;
    v_sql    varchar2(500char);
    v_id     varchar2(30char);
  begin
    v_id  := acc_main.get_acc_object_parent_column(p_acc_parent_name => p_parent_object_name);
    v_sql := 'select count(1) from dual where exists     
(select p.id_ from ' ||
             acc_main.get_acc_object_table(p_object_name) || ' p where p.' || v_id ||
             ' = ' || p_id || q'[ and p.active_ = 'Y')]';
    execute immediate v_sql
      into v_result;
    if v_result = 1 then
      return 'Y';
    end if;
    return 'N';
  exception
    when others then
      raise_application_error(-20001,'ERROR  CHECK OBJECT ACTIVITY!!!', true);
  end;

  function check_object_activity(p_id          number,
                                 p_object_name varchar2) return varchar2 as
    v_result varchar2(1 char);
  begin
    v_result := check_object_activity(p_id                 => p_id,
                                      p_object_name        => p_object_name,
                                      p_parent_object_name => 'NONE');
    return v_result;
  
  end;

  function check_exsts_act_alloc_by_artcl(p_article_id acc_allocations_t.article_id_%type)
    return varchar2 as
    v_result varchar2(1 char);
  begin
    select count(active_)
      into v_result
      from acc_allocations_t a
     where a.active_ = 'Y'
       and a.article_id_ = p_article_id;
    if v_result > 0 then
      return 'Y';
    else
      return 'N';
    end if;
  exception
    when others then
      raise_application_error(-20001,'ERROR  CHECK EXISTS ACTIVE ALLOCATION BY ALLOCATION ARTICLE!!!', true);
  end;

begin
  null;
end acc_checkers;

/
--------------------------------------------------------
--  DDL for Package Body ACC_MAIN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ASSISTANT"."ACC_MAIN" is
  -- Author  : DKHARIN
  -- Created : 08.03.2014 18:35:51
  -- Purpose : ACCOUNTENT

  custom_error exception;

  function get_lookup_value(p_lookup_name    varchar2,
                            p_lookup_display varchar2) return varchar2 as
    v_result varchar2(30 char);
  begin
    select l.value_return_
      into v_result
      from acc_lookup_t l
     where upper(l.value_display_) = upper(p_lookup_display)
       and upper(l.name_) = upper(p_lookup_name);
    return v_result;
  exception
    when others then
      raise_application_error(-20001, 'ERROR GET LOOKUP VALUE!!!', true);
  end;

  function get_acc_object_currency(p_id number, p_object_name varchar2)
    return varchar2 as
    v_result varchar2(3 char);
    v_sql    varchar2(500 char);
  begin
    v_sql := 'select p.curren_ from ' ||
             acc_main.get_acc_object_table(p_object_name) ||
             ' p where p.id_ = ' || p_id;
    execute immediate v_sql
      into v_result;
    if v_result is not null then
      return v_result;
    end if;
  exception
    when others then
      raise_application_error(-20001, 'ERROR GET CURRENCY!!!', true);
  end;

  function get_acc_object_summ(p_id number, p_object_name varchar2)
    return varchar2 as
    v_result number;
    v_sql    varchar2(500 char);
  begin
    v_sql := 'select p.summ_ from ' ||
             acc_main.get_acc_object_table(p_object_name) ||
             ' p where p.id_ = ' || p_id;
    execute immediate v_sql
      into v_result;
    if v_result is not null then
      return v_result;
    end if;
  exception
    when others then
      raise_application_error(-20001, 'ERROR GET SUMM!!!', true);
  end;

  function get_acc_object_table(p_acc_object_name varchar2) return varchar2 as
    v_result varchar2(30 char);
  begin
    v_result := get_lookup_value(p_lookup_name    => 'ACC_OBJECTS',
                                 p_lookup_display => p_acc_object_name);
    return v_result;
  exception
    when others then
      raise_application_error(-20001, 'ERROR GET TABLE!!!', true);
  end;

  function get_acc_object_parent_column(p_acc_parent_name varchar2)
    return varchar2 as
    v_result varchar2(30 char);
  begin
    v_result := get_lookup_value(p_lookup_name    => 'ACC_OBJECTS_PARENT_COLUMNS',
                                 p_lookup_display => p_acc_parent_name);
    return v_result;
  exception
    when others then
      raise_application_error(-20001, 'ERROR GET COLUMN!!!', true);
  end;

  function get_currency_qoute(p_abriveature acc_currency_t.abriveature_%type)
    return number as
    v_result number;
  begin
    select c.qoute_
      into v_result
      from acc_currency_t c
     where c.abriveature_ = p_abriveature;
    return v_result;
  exception
    when others then
      raise_application_error(-20001, 'ERROR GET CURRENCY QOUTE!!!', true);
  end;

  procedure allocation_article_add(p_name              acc_allocation_articles_t.name_%type,
                                   p_periodical        acc_allocation_articles_t.periodical_%type,
                                   p_start_date        acc_allocation_articles_t.start_date_%type,
                                   p_parent_article_id acc_allocation_articles_t.parent_article_id_%type) as
    v_id     acc_allocation_articles_t.id_%type := acc_allocation_articles_s.nextval;
    v_active acc_allocation_articles_t.active_%type := 'Y';
  begin
    /*if 'N' =
       acc_checkers.check_object_exists(p_id          => p_parent_article_id,
                                        p_object_name => 'ALLOCATION_ARTICLE') then
      raise_application_error(-20001,
                              'ERROR | CPECIFIED PARENT ALLOCATION ARTICLE NOT EXISTS ! p_parent_article_id :' ||
                              p_parent_article_id,
                              true);
    end if;
    */
    insert into acc_allocation_articles_t
      (id_, name_, periodical_, start_date_, active_, parent_article_id_)
    values
      (v_id,
       p_name,
       p_periodical,
       p_start_date,
       v_active,
       p_parent_article_id);
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR ADD ALLOCATION ARTICLE!!!',
                              true);
  end;

  procedure allocation_article_upd(p_id                acc_allocation_articles_t.id_%type,
                                   p_name              acc_allocation_articles_t.name_%type,
                                   p_periodical        acc_allocation_articles_t.periodical_%type,
                                   p_start_date        acc_allocation_articles_t.start_date_%type,
                                   p_active            acc_allocation_articles_t.active_%type,
                                   p_parent_article_id acc_allocation_articles_t.parent_article_id_%type) as
  
  begin
    if 'N' =
       acc_checkers.check_object_exists(p_id          => p_id,
                                        p_object_name => 'ALLOCATION_ARTICLE') then
      raise_application_error(-20001, 'ERROR | object not found', true);
    end if;
    if 'N' =
       acc_checkers.check_object_exists(p_id          => p_parent_article_id,
                                        p_object_name => 'ALLOCATION_ARTICLE') then
      raise_application_error(-20001,
                              'ERROR | CPECIFIED PARENT ALLOCATION ARTICLE NOT EXISTS ! p_parent_article_id :' ||
                              p_parent_article_id,
                              true);
    end if;
    if p_active = 'N' and
       'Y' =
       acc_checkers.check_exsts_act_alloc_by_artcl(p_article_id => p_id) then
      raise_application_error(-20001,
                              'ERROR | exists depended allocation',
                              true);
    end if;
    update acc_allocation_articles_t a
       set a.name_              = p_name,
           a.periodical_        = p_periodical,
           a.start_date_        = p_start_date,
           a.active_            = p_active,
           a.parent_article_id_ = p_parent_article_id
     where a.id_ = p_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | failed update allocation article',
                              true);
  end;

  procedure allocation_add(p_name       acc_allocations_t.name_%type,
                           p_article_id acc_allocations_t.article_id_%type,
                           p_date       acc_allocations_t.date_%type,
                           p_mandatory  acc_allocations_t.mandatory_%type,
                           p_summ       acc_allocations_t.summ_%type,
                           p_curren     acc_allocations_t.curren_%type) as
    v_id     acc_allocations_t.id_%type := acc_allocations_s.nextval;
    v_active acc_allocations_t.active_%type := 'Y';
    v_date   acc_allocations_t.date_%type := sysdate;
    v_manual acc_allocations_t.manual_%type := 'Y';
  begin
    if p_date is not null then
      v_date := p_date;
    end if;
    insert into acc_allocations_t
      (id_,
       name_,
       article_id_,
       date_,
       summ_,
       curren_,
       mandatory_,
       active_,
       manual_)
    values
      (v_id,
       p_name,
       p_article_id,
       v_date,
       p_summ,
       p_curren,
       p_mandatory,
       v_active,
       v_manual);
  exception
    when others then
      raise_application_error(-20001, 'ERROR | ALLOCATION ADD', true);
  end;

  procedure allocation_upd(p_id         acc_allocations_t.id_%type,
                           p_name       acc_allocations_t.name_%type,
                           p_article_id acc_allocations_t.article_id_%type,
                           p_date       acc_allocations_t.date_%type,
                           p_mandatory  acc_allocations_t.mandatory_%type,
                           p_summ       acc_allocations_t.summ_%type,
                           p_active     acc_allocations_t.active_%type) as
    v_summ      acc_allocations_v.summ_%type;
    v_pays_summ acc_allocations_v.summ_have_%type;
    v_summ_min  acc_allocations_v.summ_min_%type;
    v_curren    acc_allocations_v.curren_%type;
  begin
    --!! check that protect active (check min, pays, summ)
    if 'Y' <>
       acc_checkers.check_object_exists(p_id          => p_id,
                                        p_object_name => 'ALLOCATION') then
      raise_application_error(-20001,
                              'ERROR | CPECIFIED ALLOCATION NOT FOUND',
                              true);
    end if;
    select t.summ_, t.summ_have_, t.summ_min_, t.curren_
      into v_summ, v_pays_summ, v_summ_min, v_curren
      from acc_allocations_v t
     where t.id_ = p_id;
    if 'Y' =
       acc_checkers.check_object_exists(p_id                 => p_id,
                                        p_object_name        => 'MINUS_HEADERS',
                                        p_parent_object_name => 'ALLOCATION') then
      if p_summ < v_summ_min then
        raise_application_error(-20001,
                                'ERROR | NEED MORE GOLD!!! NOT LESS THEN ' ||
                                v_summ_min || v_curren,
                                true);
      end if;
    end if;
    update acc_allocations_t a
       set a.name_       = p_name,
           a.article_id_ = p_article_id,
           a.date_       = p_date,
           a.summ_       = p_summ,
           a.mandatory_  = p_mandatory,
           a.active_     = p_active
     where a.id_ = p_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | FAILED ALLOCATION UPDATE',
                              true);
  end;

  procedure allocation_pay_add(p_alloc_id  acc_allocation_pays_t.alloc_id_%type,
                               p_summ      acc_allocation_pays_t.summ_%type,
                               p_pocket_id acc_allocation_pays_t.pocket_id_%type) as
    v_id         acc_allocation_pays_t.id_%type := acc_allocation_pays_s.nextval;
    v_active     acc_allocation_pays_t.active_%type := 'Y';
    v_curren     acc_allocation_pays_t.curren_%type := get_acc_object_currency(p_pocket_id,
                                                                               'POCKET');
    v_summ_minus acc_allocation_pays_t.summ_minus_%type := 0;
  begin
    if 'N' =
       acc_checkers.check_object_activity(p_id          => p_pocket_id,
                                          p_object_name => 'POCKET') then
      raise_application_error(-20001,
                              'ERROR | CPECIFIED POCKET NOT ACTIVITY',
                              true);
    end if;
    if v_curren <> get_acc_object_currency(p_alloc_id, 'ALLOCATION') then
      raise_application_error(-20001,
                              'ERROR | NOT MATCH CURRENS ALLOCATION PAY and POCKET',
                              true);
    end if;
    if p_summ > get_acc_object_summ(p_pocket_id, 'POCKET') then
      raise_application_error(-20001,
                              'ERROR | SUMM ALLOCATION PAY GRATHER SUMM POCKET',
                              true);
    end if;
    insert into acc_allocation_pays_t
      (id_, alloc_id_, summ_, curren_, pocket_id_, active_, summ_minus_)
    values
      (v_id,
       p_alloc_id,
       p_summ,
       v_curren,
       p_pocket_id,
       v_active,
       v_summ_minus);
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | ALLOCATION PAY ADD FAILED',
                              true);
  end;

  procedure allocation_pay_upd(p_id         acc_allocation_pays_t.id_%type,
                               p_summ       acc_allocation_pays_t.summ_%type,
                               p_pocket_id  acc_allocation_pays_t.pocket_id_%type,
                               p_summ_minus acc_allocation_pays_t.summ_minus_%type) as
    v_pck_summ_avlb acc_allocation_pays_v.pck_summ_avlb_%type;
    v_alloc_summ    acc_allocation_pays_v.summ_alloc_%type;
    v_summ_pay      acc_allocation_pays_v.summ_pay_%type;
    v_curren        acc_allocation_pays_v.curren_%type := get_acc_object_currency(p_id          => p_id,
                                                                                  p_object_name => 'ALLOCATION_PAY');
  
    v_summ_min acc_allocations_v.summ_min_%type;
  begin
    select ap.summ_pay_, ap.pck_summ_avlb_, ap.summ_alloc_
      into v_summ_pay, v_pck_summ_avlb, v_alloc_summ
      from acc_allocation_pays_v ap
     where ap.id_ = p_id;
    if v_curren <>
       get_acc_object_currency(p_id          => p_pocket_id,
                               p_object_name => 'POCKET') then
      raise_application_error(-20001,
                              'ERROR | WRONG CURRENCY SELECTED ALLOCATION POCKET',
                              true);
    end if;
    if p_summ > (v_pck_summ_avlb + v_summ_pay) then
      raise_application_error(-20001,
                              'ERROR | SUMM ALLOCATION PAY GRATHER SUMM POCKET !!!',
                              true);
    end if;
  
    select a.summ_min_
      into v_summ_min
      from acc_allocations_v a
     where a.id_ = p_id;
    if p_summ > v_summ_min then
      raise_application_error(-20001,
                              'ERROR | SUMM MINUS GRATHER SUMM ALLOCATION !!!',
                              true);
    end if;
  
    /*    dbms_output.put_line(p_summ || ',' || p_pocket_id || ',' ||
    p_summ_minus);*/
    update acc_allocation_pays_t ap
       set ap.summ_       = p_summ,
           ap.pocket_id_  = p_pocket_id,
           ap.summ_minus_ = p_summ_minus
     where ap.id_ = p_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | ERROR  ALLOCATION PAY UPD!!!',
                              true);
  end;

  procedure allocation_pay_deactive(p_id acc_allocation_pays_t.id_%type) as
  begin
    if 'N' =
       acc_checkers.check_object_exists(p_id          => p_id,
                                        p_object_name => 'ALLOCATION_PAY') then
      raise_application_error(-20001,
                              'ERROR | ERROR ALLOCATION PAY NOT EXISTS!!!',
                              true);
    end if;
    update acc_allocation_pays_t ap
       set ap.active_ = 'N'
     where ap.id_ = p_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | ERROR  ALLOCATION PAY DEACTIVE!!!',
                              true);
  end;

  procedure credit_add(p_who_id       acc_credits_t.who_id_%type,
                       p_summ         acc_credits_t.summ_%type,
                       p_dead_line    acc_credits_t.dead_line_%type,
                       p_pocket_id    acc_credits_t.pocket_id_%type,
                       p_profit_type  acc_credits_t.profit_type_%type,
                       p_profit_value acc_credits_t.profit_value_%type,
                       p_when         acc_credits_t.when_%type) as
    v_summ_avlb acc_pockets_v.summ_avlb_%type;
  begin
    select p.summ_avlb_
      into v_summ_avlb
      from acc_pockets_v p
     where p.id_ = p_pocket_id;
    if p_summ <= v_summ_avlb then
      insert into acc_credits_t
        (who_id_,
         summ_,
         dead_line_,
         pocket_id_,
         profit_type_,
         profit_value_,
         when_)
      values
        (p_who_id,
         p_summ,
         p_dead_line,
         p_pocket_id,
         p_profit_type,
         p_profit_value,
         p_when);
    else
      null;
    end if;
  exception
    when others then
      raise_application_error(-20001, 'ERROR | ERROR  CREDIT ADD!!!', true);
  end;

  procedure kind_store_add(p_name acc_kinds_store_t.name_%type) as
    v_id acc_kinds_store_t.id_%type := acc_kinds_store_s.nextval;
  begin
    insert into acc_kinds_store_t
      (id_, name_)
    values
      (v_id, upper(p_name));
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | ERROR  KIND STORE ADD!!!',
                              true);
  end;

  procedure kind_store_upd(p_id   acc_kinds_store_t.id_%type,
                           p_name acc_kinds_store_t.name_%type) as
  begin
    if 'N' =
       acc_checkers.check_object_exists(p_id          => p_id,
                                        p_object_name => 'KIND_STORE') then
      raise_application_error(-20001,
                              'ERROR | SPECIFIED KIND STORE NOT EXISTS | kind_sore_id: ' || p_id,
                              true);
    end if;
    if 'Y' =
       acc_checkers.check_object_exists(p_id                 => p_id,
                                        p_object_name        => 'POCKET',
                                        p_parent_object_name => 'KIND_STORE') then
      raise_application_error(-20001,
                              'ERROR | EXISTS DEPENDING POCKET !!!',
                              true);
    end if;
    update acc_kinds_store_t ks
       set ks.name_ = upper(p_name)
     where ks.id_ = p_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | ERROR  KIND STORE UPDATE!!!',
                              true);
  end;

  procedure kind_store_del(p_id acc_kinds_store_t.id_%type) as
  begin
    if 'N' =
       acc_checkers.check_object_exists(p_id          => p_id,
                                        p_object_name => 'KIND_STORE') then
      raise_application_error(-20001,
                              'ERROR | SPECIFIED KIND STORE NOT EXISTS !!!',
                              true);
    end if;
    if 'Y' =
       acc_checkers.check_object_exists(p_id                 => p_id,
                                        p_object_name        => 'POCKET',
                                        p_parent_object_name => 'KIND_STORE') then
      raise_application_error(-20001,
                              'ERROR | EXISTS DEPENDED POCKET',
                              true);
    end if;
    delete from acc_kinds_store_t ks where ks.id_ = p_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR | ERROR  DELETE KIND STORE!!!',
                              true);
  end;

  procedure pocket_add(p_name          acc_pockets_t.name_%type,
                       p_kind_store_id acc_pockets_t.kind_store_id_%type,
                       p_summ          acc_pockets_t.summ_%type,
                       p_curren        acc_pockets_t.curren_%type) as
    v_id     acc_pockets_t.id_%type := acc_pockets_s.nextval;
    v_active acc_pockets_t.active_%type := 'Y';
  begin
    insert into acc_pockets_t
      (id_, name_, kind_store_id_, summ_, curren_, active_)
    values
      (v_id, p_name, p_kind_store_id, p_summ, p_curren, v_active);
  exception
    when others then
      raise_application_error(-20001, 'ERROR  POCKET ADD!!!', false);
  end;

  procedure pocket_upd(p_id            acc_pockets_t.id_%type,
                       p_name          acc_pockets_t.name_%type,
                       p_kind_store_id acc_pockets_t.kind_store_id_%type,
                       p_summ          acc_pockets_t.summ_%type,
                       p_active        acc_pockets_t.active_%type) as
    v_summ_busy acc_pockets_v.summ_busy_%type;
    v_summ      acc_pockets_v.summ_%type;
  begin
    if 'N' =
       acc_checkers.check_object_exists(p_id          => p_id,
                                        p_object_name => 'POCKET') then
      raise_application_error(-20001,
                              'ERROR | SPECIFIED POCKET NOT EXISTS !!!',
                              true);
    end if;
    --!! check protect active
    if 'Y' =
       acc_checkers.check_object_exists(p_id                 => p_id,
                                        p_object_name        => 'ALLOCATION_PAY',
                                        p_parent_object_name => 'POCKET') then
      select p.summ_, p.summ_busy_
        into v_summ, v_summ_busy
        from acc_pockets_v p
       where p.id_ = p_id;
      -- !! credit summ
      if p_summ < v_summ_busy then
        raise_application_error(-20001,
                                'SUMM LESS THAN SUMM DEPENDENT ALLOCATION PAY !!!',
                                true);
      end if;
    end if;
    update acc_pockets_t p
       set p.name_          = p_name,
           p.kind_store_id_ = p_kind_store_id,
           p.summ_          = p_summ,
           p.active_        = p_active
     where p.id_ = p_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR  |  ERROR POCKET UPDATE',
                              true);
  end;

  procedure minus_add(p_alloc_id   acc_minus_headers_t.alloc_id_%type,
                      p_date       acc_minus_headers_t.date_%type,
                      p_summ       acc_minus_headers_t.summ_%type,
                      p_comment    acc_minus_headers_t.comment_%type,
                      p_curr_quote acc_minus_headers_t.curr_quote_%type) as
    cursor c_all_pays is
      select *
        from acc_allocation_pays_v ap
       where ap.alloc_id_ = p_alloc_id
         and ap.active_ = 'Y';
    v_all_pay        acc_allocation_pays_v%rowtype;
    v_summ_spend     acc_minus_headers_t.summ_%type := 0;
    v_summ_spend_cur acc_minus_headers_t.summ_%type := 0;
    v_summ_have      number;
    v_minus_id       acc_minus_headers_t.id_%type;
  begin
    if 'Y' <>
       acc_checkers.check_object_activity(p_id          => p_alloc_id,
                                          p_object_name => 'ALLOCATION') then
      raise_application_error(-20001,
                              'ERROR  | ALLOCATION NOT ACTIVE !!!',
                              true);
    end if;
    select summ_have_
      into v_summ_have
      from acc_allocations_v a
     where a.id_ = p_alloc_id;
    if v_summ_have < p_summ then
      raise_application_error(-20001,
                              'ERROR  |  INSUFFICIENT ALLOCATED MONEY !!!',
                              true);
    end if;
    v_minus_id := minus_header_add(p_alloc_id => p_alloc_id,
                                   p_date     => p_date,
                                   p_summ     => p_summ,
                                   p_comment  => p_comment);
    open c_all_pays;
    loop
      fetch c_all_pays
        into v_all_pay;
      if v_all_pay.summ_pay_ <=
         (v_all_pay.summ_minus_ + p_summ - v_summ_spend) then
        v_summ_spend_cur := v_all_pay.summ_pay_ - v_all_pay.summ_minus_;
        allocation_pay_upd(p_id         => v_all_pay.id_,
                           p_summ       => v_all_pay.summ_pay_,
                           p_pocket_id  => v_all_pay.pocket_id_,
                           p_summ_minus => v_all_pay.summ_pay_);
        minus_sites_add(p_minus_id     => v_minus_id,
                        p_alloc_pay_id => v_all_pay.id_,
                        p_summ         => v_summ_spend_cur,
                        p_comment      => '');
        pocket_upd(p_id            => v_all_pay.pocket_id_,
                   p_name          => v_all_pay.pck_name_,
                   p_kind_store_id => v_all_pay.pck_kind_store_id_,
                   p_summ          => (v_all_pay.pck_summ_ -
                                      v_summ_spend_cur),
                   p_active        => v_all_pay.pck_active_);
        allocation_pay_deactive(p_id => v_all_pay.id_);
        v_summ_spend := v_summ_spend + v_summ_spend_cur;
      else
        v_summ_spend_cur := p_summ - v_summ_spend;
        allocation_pay_upd(p_id         => v_all_pay.id_,
                           p_summ       => v_all_pay.summ_pay_,
                           p_pocket_id  => v_all_pay.pocket_id_,
                           p_summ_minus => (v_all_pay.summ_minus_ + p_summ -
                                           v_summ_spend));
        minus_sites_add(p_minus_id     => v_minus_id,
                        p_alloc_pay_id => v_all_pay.id_,
                        p_summ         => v_summ_spend_cur,
                        p_comment      => '');
        pocket_upd(p_id            => v_all_pay.pocket_id_,
                   p_name          => v_all_pay.pck_name_,
                   p_kind_store_id => v_all_pay.pck_kind_store_id_,
                   p_summ          => (v_all_pay.pck_summ_ -
                                      v_summ_spend_cur),
                   p_active        => v_all_pay.pck_active_);
        v_summ_spend := p_summ;
      end if;
      exit when v_summ_spend = p_summ;
    end loop;
    close c_all_pays;
  exception
    when others then
      raise_application_error(-20001, 'ERROR  |  FAILED MINUS ADD', true);
  end;

  function minus_header_add(p_alloc_id acc_minus_headers_t.alloc_id_%type,
                            p_date     acc_minus_headers_t.date_%type,
                            p_summ     acc_minus_headers_t.summ_%type,
                            p_comment  acc_minus_headers_t.comment_%type)
    return number as
    v_id         acc_minus_headers_t.id_%type := acc_minus_headers_s.nextval;
    v_curren     acc_allocations_t.curren_%type := get_acc_object_currency(p_id          => p_alloc_id,
                                                                           p_object_name => 'ALLOCATION');
    v_curr_quote acc_minus_headers_t.curr_quote_%type;
  begin
    --!! summ
    --!! refactor curr_quote (history)
    v_curr_quote := get_currency_qoute(p_abriveature => v_curren);
    insert into acc_minus_headers_t
      (id_, alloc_id_, date_, summ_, comment_, curr_quote_)
    values
      (v_id, p_alloc_id, p_date, p_summ, p_comment, v_curr_quote);
    return v_id;
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR  |  FAILED MINUS HEADER ADD',
                              true);
  end;

  procedure minus_sites_add(p_minus_id     acc_minus_sites_t.minus_id_%type,
                            p_alloc_pay_id acc_minus_sites_t.alloc_pay_id_%type,
                            p_summ         acc_minus_sites_t.summ_%type,
                            p_comment      acc_minus_sites_t.comment_%type) as
    v_id acc_minus_sites_t.minus_id_%type := acc_minus_sites_s.nextval;
  begin
    insert into acc_minus_sites_t
      (id_, minus_id_, alloc_pay_id_, summ_, comment_)
    values
      (v_id, p_minus_id, p_alloc_pay_id, p_summ, p_comment);
  exception
    when others then
      raise_application_error(-20001,
                              'ERROR  |  FAILED MINUS SITE ADD',
                              true);
  end;
begin
  null;
end acc_main;

/
